"""add enrolled_at to student_subjects

Revision ID: 90be7827e7f6
Revises: 1cff8173de4c
Create Date: 2026-09-23 22:54:05.403760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90be7827e7f6'
down_revision: Union[str, Sequence[str], None] = '1cff8173de4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_subjects', sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_subjects', 'enrolled_at')
    # ### end Alembic commands ###
